[package]
name = "relua"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.11.1"
graphviz-rust = "0.6.2"
relua-macros = { path = 'relua-macros', version = '0.1.0 ' }
